### ISSUE TITLE
新版 Zoom 中，通过 url 加入会议会导致中文名字乱码

### ISSUE THREAD

**Issue by izackwu** [skyzh/zoom-url-generator#2]
![image](https://user-images.githubusercontent.com/20233656/78846379-2d03b480-7a3e-11ea-984f-cbb057a0539c.png)

**Comment by skyzh** [comment]
Thanks for your report! I'll look into this soon.

**Comment by skyzh** [comment]
I've just tested this URL to join my personal meeting room on my Windows virtual machine. It seems to be alright.

```
zoommtg://zoom.us/join?confno=8529015944&pwd=&uname=%E8%BF%9F%E7%AD%96%20-%2051800000000
```

![image](https://user-images.githubusercontent.com/4198311/78847841-98e81c00-7a42-11ea-988c-3d1a75f69604.png)
![image](https://user-images.githubusercontent.com/4198311/78847866-a8676500-7a42-11ea-8e6f-32d6de4de0f6.png)

Would you please tell which version you're using, and check your regions settings?

**Comment by izackwu** [comment]
Well, joining with URL worked perfectly for me until updating Zoom this week. 

Currently, my Zoom version is `Version: 4.6.10 (20033.0407)` on Windows 10. And my computer's language is set to English.

**Comment by skyzh** [comment]
![image](https://user-images.githubusercontent.com/4198311/78848648-f715fe80-7a44-11ea-9d1f-9865b2124309.png)

What about locale settings? I guess that you might have enabled UTF-8 support.

**Comment by izackwu** [comment]
![image](https://user-images.githubusercontent.com/20233656/78848764-4eb46a00-7a45-11ea-8c61-938a967d0e1e.png)

**Comment by skyzh** [comment]
I've changed my locale to Chinese (Simplified) and entered the meeting room again. Things goes well on my PC. I have no idea what's happening :(

**Comment by izackwu** [comment]
> 
> 
> I've changed my locale to Chinese (Simplified) and entered the meeting room again. Things goes well on my PC. I have no idea what's happening :(

Thank you anyway~

**Comment by izackwu** [comment]
@skyzh  Oh, maybe I have found the weird bug:

If I start from Firefox, the URL won't work; but for Edge, it works as expected. And I guess you tested it with Chrome, which also works perfectly? So, there's something wrong with Firefox? 😂

**Comment by skyzh** [comment]
Yes, I suspect that Firefox passed the decoded URL to Zoom (instead of %aa%aa%aa). Again, thanks for your report!

**Comment by skyzh** [comment]
I've made a PR to warn Firefox users. Close this issue for now.
